#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Write the case-study lists into the index pages as static HTML.

Every locale's case-studies.html built its list at runtime by calling
https://api.github.com/repos/.../contents/<folder>. That put core navigation
behind a third party: the unauthenticated GitHub API allows 60 requests an
hour per IP, so a shared or office IP can exhaust it and a first-time visitor
(who has no localStorage cache to fall back on) then sees an error instead of
the list. It also left the index pages with no links in their HTML at all,
which is a poor position to be in for crawling.

This writes the list into the page between two markers. The existing script
still runs and replaces the list when the API answers, so nothing is lost -
but the page is now complete and linked without it.

    python3 tools/build-case-lists.py
"""
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = '<!-- case-list:begin (generated by tools/build-case-lists.py) -->'
END = '<!-- case-list:end -->'

# index page -> (folder of case studies, language suffixes to list, read-more label)
INDEXES = {
    'case-studies.html':    ('case-studies',    ('EN',),             'Read Report'),
    'ko/case-studies.html': ('ko/case-studies', ('KR', 'EN'),        '리포트 보기'),
    'jp/case-studies.html': ('jp/case-studies', ('JP', 'EN'),        'レポートを見る'),
    'es/case-studies.html': ('es/case-studies', ('ES', 'EN'),        'Ver informe'),
    'ru/case-studies.html': ('ru/case-studies', ('RU', 'EN'),        'Открыть отчёт'),
}

NAME_RE = re.compile(r'^(\d{4})-(\d{2})-(\d{2})-(.+)\.html$')
TITLE_RE = re.compile(r'<title>(.*?)</title>', re.S | re.I)
NOINDEX_RE = re.compile(r'<meta[^>]+name="robots"[^>]+content="[^"]*noindex', re.I)


def page_title(path):
    """The real <title>, minus the site suffix - better than the JS fallback,
    which just turns the filename's hyphens into spaces."""
    with open(path, encoding='utf-8', errors='ignore') as fh:
        head = fh.read(8192)
    if NOINDEX_RE.search(head):
        return None
    m = TITLE_RE.search(head)
    if not m:
        return None
    title = html.unescape(' '.join(m.group(1).split()))
    for sep in (' | ', ' — ', ' – '):
        if sep in title:
            title = title.split(sep)[0].strip()
            break
    return title


def collect(folder, langs):
    d = os.path.join(ROOT, folder)
    if not os.path.isdir(d):
        return []
    items = []
    for name in os.listdir(d):
        m = NAME_RE.match(name)
        if not m:
            continue
        y, mo, dy, key = m.groups()
        lang = key.rsplit('-', 1)[-1]
        if lang not in langs:
            continue
        title = page_title(os.path.join(d, name))
        if not title:
            continue
        items.append(((y, mo, dy), f'{y}.{mo}.{dy}', title, f'/{folder}/{name}'))
    items.sort(reverse=True)
    return items


def render(items, more_label):
    out = [BEGIN]
    for _, date_str, title, url in items:
        out.append(
            '        <div class="report-item">\n'
            f'          <div class="report-date">{date_str}</div>\n'
            '          <div class="report-main">\n'
            f'            <h3 class="report-title"><a href="{html.escape(url)}" class="title-link">'
            f'{html.escape(title)}</a></h3>\n'
            '          </div>\n'
            f'          <div class="report-link"><a href="{html.escape(url)}" '
            f'class="btn btn-primary btn-small">{html.escape(more_label)} &rarr;</a></div>\n'
            '        </div>'
        )
    out.append('        ' + END)
    return '\n'.join(out)


def main():
    total = 0
    for index, (folder, langs, more_label) in INDEXES.items():
        path = os.path.join(ROOT, index)
        if not os.path.exists(path):
            print(f'  skip (missing) {index}')
            continue
        items = collect(folder, langs)
        block = render(items, more_label)

        with open(path, encoding='utf-8', newline='') as fh:
            raw = fh.read()

        if BEGIN in raw and END in raw:
            new = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), block, raw, flags=re.S)
        else:
            m = re.search(r'(<div id="caseStudiesContainer"[^>]*>)(.*?)(</div>)', raw, re.S)
            if not m:
                print(f'  ! container not found in {index}')
                continue
            new = raw[:m.end(1)] + '\n' + block + '\n      ' + raw[m.start(3):]

        if new != raw:
            with open(path, 'w', encoding='utf-8', newline='') as fh:
                fh.write(new)
        print(f'  {index:<24} {len(items):>3} reports')
        total += len(items)
    print(f'\nTotal listed: {total}')


if __name__ == '__main__':
    sys.exit(main())
