#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Write the case-study lists into the index pages as static HTML.

Every locale's case-studies.html built its list at runtime by calling
https://api.github.com/repos/.../contents/<folder>. That put core navigation
behind a third party: the unauthenticated GitHub API allows 60 requests an
hour per IP, so a shared or office IP can exhaust it and a first-time visitor
(who has no localStorage cache to fall back on) then sees an error instead of
the list. It also left the index pages with no links in their HTML at all,
which is a poor position to be in for crawling.

This writes the list into the page between two markers. The existing script
still runs and replaces the list when the API answers, so nothing is lost -
but the page is now complete and linked without it.

    python3 tools/build-case-lists.py
"""
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = '<!-- case-list:begin (generated by tools/build-case-lists.py) -->'
END = '<!-- case-list:end -->'

# index page -> (folder of case studies, language suffixes to list, read-more label)
INDEXES = {
    'case-studies.html':    ('case-studies',    ('EN',),             'Read Report'),
    'ko/case-studies.html': ('ko/case-studies', ('KR', 'EN'),        '리포트 보기'),
    'jp/case-studies.html': ('jp/case-studies', ('JP', 'EN'),        'レポートを見る'),
    'es/case-studies.html': ('es/case-studies', ('ES', 'EN'),        'Ver informe'),
    'ru/case-studies.html': ('ru/case-studies', ('RU', 'EN'),        'Открыть отчёт'),
}

# Clinical field of each article, keyed by the slug stem shared across locales.
# Kept here rather than in a meta tag on 90-odd article files: the index is
# generated from this script anyway, so one table is the single place to edit
# when a new article lands. A stem absent from the map falls into 'other' and
# still shows under "All".
CATEGORY = {
    'Busan-Frailty-Health-Up': 'community',
    'Mokdong-Frailty': 'community',
    'Seongdong-Nofrailty': 'community',
    'Pyeongchang-Multicomponent-Frailty': 'community',
    'Seoul-Home-Visit-Health-Frailty-Status': 'community',
    'Community-Frailty-Prevention-Program': 'community',
    'Checkup-Event-Community-CSR': 'community',
    'Japan-CSR-Frailty-Prevention': 'community',
    'Japan-Asahi': 'community',
    'Hongkong-Frailty-Prevention-CADENZA': 'community',
    'SPPB-Community-Frailty-Management': 'community',
    '4Ms-Framework-Community': 'community',
    'Digital-Care-Platform': 'community',

    'Frailty-Policy': 'policy',
    'Japan-Frailty-Prevention-Policy': 'policy',
    'ICOPE-France': 'policy',
    'Australia-Frailty-Consensus': 'policy',
    'Health-Screening-Redesign': 'policy',
    'Common-Operational-Language-Strategy': 'policy',
    'Spain-SPPB-Screening': 'policy',
    'SPPB-Utilization-Spain': 'policy',
    'Tokyo-Oral-Frailty-Manual': 'policy',
    'SPPB-Occupational-Health': 'policy',

    'Sarcopenia-Drug-Development-SPPB': 'research',
    'Sarcopenia-Management-Korea': 'research',
    'BNR17-Muscle-Function-Older-Adults': 'research',
    'PRO-SPPB-Linking-Study': 'research',
    'Lancet-Accelerated-Frailty-Deficit': 'research',
    'CIBERFES-Consensus-Frailty-Screening': 'research',
    'KAARM-Spring-Conference': 'research',
    'Pain-To-Function-Paradigm-Shift': 'research',
    'Japan-NCGG-FR-IC-Index': 'research',

    'Frailty-Cognition-Delirium-Mental-Health': 'cognition',
    'Physical-Function-Aging-Cognition': 'cognition',
    'Sarcopenia-Dementia-Meta-Analysis': 'cognition',

    'Heart-Failure-Cardiopulmonary-Rehab-SPPB': 'cardio',
    'ACC-Frailty-Cardiovascular-SPPB': 'cardio',
    'ISHLT-Lung-Transplant-Frailty-SPPB': 'cardio',

    'Perioperative-Prehabilitation-Early-Exercise-SPPB': 'surgery',
    'PGH-Colorectal-Surgery-SPPB': 'surgery',

    'Endocrinology-SPPB-Strategy': 'endocrine',
    'ADA2026-GLP1-Muscle-Loss-Debate': 'endocrine',

    'CKD-Frailty-Consensus-SPPB': 'nephrology',
    'Oncology-SPPB-AndanteFit': 'oncology',
}

CAT_ORDER = ['all', 'community', 'policy', 'research', 'cognition',
             'cardio', 'surgery', 'endocrine', 'nephrology', 'oncology', 'other']

CAT_LABELS = {
    'en': {'all': 'All', 'community': 'Community programmes', 'policy': 'Policy & systems',
           'research': 'Sarcopenia & research', 'cognition': 'Cognition', 'cardio': 'Cardio-respiratory',
           'surgery': 'Surgery & perioperative', 'endocrine': 'Endocrine & metabolic',
           'nephrology': 'Nephrology', 'oncology': 'Oncology', 'other': 'Other',
           'aria': 'Filter case studies by field'},
    'ko': {'all': '전체', 'community': '지역사회 프로그램', 'policy': '정책·제도',
           'research': '근감소증·연구', 'cognition': '인지·신경', 'cardio': '순환기·호흡기',
           'surgery': '외과·수술 전후', 'endocrine': '내분비·대사',
           'nephrology': '신장', 'oncology': '종양', 'other': '기타',
           'aria': '분야별로 사례 걸러 보기'},
    'jp': {'all': 'すべて', 'community': '地域プログラム', 'policy': '政策・制度',
           'research': 'サルコペニア・研究', 'cognition': '認知・神経', 'cardio': '循環器・呼吸器',
           'surgery': '外科・周術期', 'endocrine': '内分泌・代謝',
           'nephrology': '腎臓', 'oncology': '腫瘍', 'other': 'その他',
           'aria': '分野で絞り込む'},
    'es': {'all': 'Todos', 'community': 'Programas comunitarios', 'policy': 'Políticas y sistemas',
           'research': 'Sarcopenia e investigación', 'cognition': 'Cognición', 'cardio': 'Cardiorrespiratorio',
           'surgery': 'Cirugía y perioperatorio', 'endocrine': 'Endocrino y metabólico',
           'nephrology': 'Nefrología', 'oncology': 'Oncología', 'other': 'Otros',
           'aria': 'Filtrar los casos por especialidad'},
    'ru': {'all': 'Все', 'community': 'Программы в сообществе', 'policy': 'Политика и системы',
           'research': 'Саркопения и исследования', 'cognition': 'Когнитивные функции',
           'cardio': 'Кардиореспираторные', 'surgery': 'Хирургия и периоперационный период',
           'endocrine': 'Эндокринология и метаболизм', 'nephrology': 'Нефрология',
           'oncology': 'Онкология', 'other': 'Прочее',
           'aria': 'Фильтр по направлению'},
}

FILTER_BEGIN = '<!-- case-filter:begin (generated by tools/build-case-lists.py) -->'
FILTER_END = '<!-- case-filter:end -->'

NAME_RE = re.compile(r'^(\d{4})-(\d{2})-(\d{2})-(.+)\.html$')
TITLE_RE = re.compile(r'<title>(.*?)</title>', re.S | re.I)
NOINDEX_RE = re.compile(r'<meta[^>]+name="robots"[^>]+content="[^"]*noindex', re.I)


def page_title(path):
    """The real <title>, minus the site suffix - better than the JS fallback,
    which just turns the filename's hyphens into spaces."""
    with open(path, encoding='utf-8', errors='ignore') as fh:
        head = fh.read(8192)
    if NOINDEX_RE.search(head):
        return None
    m = TITLE_RE.search(head)
    if not m:
        return None
    title = html.unescape(' '.join(m.group(1).split()))
    for sep in (' | ', ' — ', ' – '):
        if sep in title:
            title = title.split(sep)[0].strip()
            break
    return title


def collect(folder, langs):
    d = os.path.join(ROOT, folder)
    if not os.path.isdir(d):
        return []
    items = []
    for name in os.listdir(d):
        m = NAME_RE.match(name)
        if not m:
            continue
        y, mo, dy, key = m.groups()
        lang = key.rsplit('-', 1)[-1]
        if lang not in langs:
            continue
        title = page_title(os.path.join(d, name))
        if not title:
            continue
        stem = key.rsplit('-', 1)[0] if lang else key
        cat = CATEGORY.get(stem, 'other')
        items.append(((y, mo, dy), f'{y}.{mo}.{dy}', title, f'/{folder}/{name}', cat))
    items.sort(reverse=True)
    return items


def render(items, more_label):
    out = [BEGIN]
    for _, date_str, title, url, cat in items:
        out.append(
            f'        <div class="report-item" data-category="{cat}">\n'
            f'          <div class="report-date">{date_str}</div>\n'
            '          <div class="report-main">\n'
            f'            <h3 class="report-title"><a href="{html.escape(url)}" class="title-link">'
            f'{html.escape(title)}</a></h3>\n'
            '          </div>\n'
            f'          <div class="report-link"><a href="{html.escape(url)}" '
            f'class="btn btn-primary btn-small">{html.escape(more_label)} &rarr;</a></div>\n'
            '        </div>'
        )
    out.append('        ' + END)
    return '\n'.join(out)


def render_filter(items, loc):
    """Chips for the fields this locale actually has, so a locale with four
    articles does not show ten empty filters."""
    labels = CAT_LABELS[loc]
    counts = {}
    for it in items:
        counts[it[4]] = counts.get(it[4], 0) + 1
    present = [c for c in CAT_ORDER if c != 'all' and counts.get(c)]
    if len(present) < 2:
        return FILTER_BEGIN + '\n      ' + FILTER_END
    chips = [('all', len(items))] + [(c, counts[c]) for c in present]
    out = [FILTER_BEGIN,
           f'      <div class="case-filter" role="group" aria-label="{html.escape(labels["aria"])}">']
    for key, n in chips:
        active = ' is-active' if key == 'all' else ''
        pressed = 'true' if key == 'all' else 'false'
        out.append(
            f'        <button type="button" class="case-chip{active}" data-filter="{key}" '
            f'aria-pressed="{pressed}">{html.escape(labels[key])}'
            f'<span class="case-chip-n">{n}</span></button>')
    out.append('      </div>')
    out.append("""      <script>
      (function () {
        var wrap = document.currentScript.previousElementSibling;
        if (!wrap || !wrap.classList.contains('case-filter')) return;
        wrap.addEventListener('click', function (e) {
          // Looked up here, not at parse time: this script runs before the
          // list container below it has been parsed.
          var list = document.getElementById('caseStudiesContainer');
          if (!list) return;
          var btn = e.target.closest('.case-chip');
          if (!btn) return;
          var want = btn.getAttribute('data-filter');
          wrap.querySelectorAll('.case-chip').forEach(function (c) {
            var on = c === btn;
            c.classList.toggle('is-active', on);
            c.setAttribute('aria-pressed', on ? 'true' : 'false');
          });
          list.querySelectorAll('.report-item').forEach(function (item) {
            item.hidden = want !== 'all' && item.getAttribute('data-category') !== want;
          });
        });
      })();
      </script>""")
    out.append('      ' + FILTER_END)
    return '\n'.join(out)


def main():
    total = 0
    for index, (folder, langs, more_label) in INDEXES.items():
        path = os.path.join(ROOT, index)
        if not os.path.exists(path):
            print(f'  skip (missing) {index}')
            continue
        loc = index.split('/')[0] if '/' in index else 'en'
        items = collect(folder, langs)
        block = render(items, more_label)
        fblock = render_filter(items, loc)

        with open(path, encoding='utf-8', newline='') as fh:
            raw = fh.read()
        original = raw

        # The chips sit outside the list container, which carries a top border
        # and would otherwise draw a rule above them.
        if FILTER_BEGIN in raw and FILTER_END in raw:
            raw = re.sub(re.escape(FILTER_BEGIN) + r'.*?' + re.escape(FILTER_END),
                         fblock, raw, flags=re.S)
        else:
            anchor = re.search(r'([ \t]*)<div id="caseStudiesContainer"', raw)
            if anchor:
                indent = anchor.group(1)
                raw = raw[:anchor.start()] + fblock + '\n' + indent + raw[anchor.start() + len(indent):]

        if BEGIN in raw and END in raw:
            new = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), block, raw, flags=re.S)
        else:
            m = re.search(r'(<div id="caseStudiesContainer"[^>]*>)(.*?)(</div>)', raw, re.S)
            if not m:
                print(f'  ! container not found in {index}')
                continue
            new = raw[:m.end(1)] + '\n' + block + '\n      ' + raw[m.start(3):]

        # Compare against the file as read, not against raw - raw already holds
        # the rewritten filter block, so a filter-only change would look like
        # no change at all and never be written.
        if new != original:
            with open(path, 'w', encoding='utf-8', newline='') as fh:
                fh.write(new)
        cats = sorted({it[4] for it in items})
        print(f'  {index:<24} {len(items):>3} reports   {", ".join(cats)}')
        total += len(items)
    print(f'\nTotal listed: {total}')


if __name__ == '__main__':
    sys.exit(main())
